name: Reporte de Mutaciones con Stryker
env:
  DOTNET_VERSION: '8.0' # la versión de .NET
on: push
# on: 
#   workflow_dispatch:
jobs:
  test-and-publish-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configurando la versión de NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies & Run tests with coverage
      run: |
        cd WebApp
        dotnet restore
        dotnet test --collect:"XPlat Code Coverage"
    - name: Install Stryker
      run: dotnet tool install -g dotnet-stryker
    - name: Generate mutation Report
      run: |
        cd WebApp
        dotnet stryker
    - name: Find Stryker report folder and move it to a fixed path
      run: |
        mkdir -p WebApp/StrykerReport
        REPORT_DIR=$(find WebApp/StrykerOutput -type d -name reports | head -n 1)
        echo "Nose encontro el reportte en: $REPORT_DIR"
        cp -r "$REPORT_DIR/"* WebApp/StrykerReport/
    - name: Deploy mutation report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: WebApp/StrykerReport
        destination_dir: Stryker
        keep_files: true