name: Semgrep Code Analysis

on: push
# on: 
#   workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    name: Semgrep Security Scan
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Semgrep
      id: semgrep
      uses: semgrep/semgrep-action@v1
      with:
        config: >
          p/security-audit
          p/secrets
          p/csharp
        generateSarif: "1"
        
    - name: Upload Semgrep results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: semgrep.sarif
        
    - name: Generate Semgrep HTML Report
      if: always()
      run: |
        pip install --upgrade semgrep
        mkdir -p semgrep-report
        semgrep scan --config=p/default --output-format=html --output=semgrep-report/index.html WebApp/ || true

    - name: Deploy Semgrep report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: semgrep-report
        destination_dir: ReporteSemgrep
        keep_files: true
